/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.demo;

import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableValue;
import edu.wpi.first.networktables.NetworkTableInstance;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
		System.out.println(new App().getGreeting());

        (new Thread(new MyRunnable())).start();

		NetworkTableInstance inst = NetworkTableInstance.getDefault();
		NetworkTable table = inst.getTable("datatable");
		NetworkTableEntry xEntry = table.getEntry("x");
		NetworkTableEntry yEntry = table.getEntry("y");
		NetworkTableEntry zEntry = table.getEntry("z");
		NetworkTableValue z = NetworkTableValue.makeDouble(1.2);
		zEntry.setValue(z);
		inst.startClient("127.0.0.1");  // where TEAM=190, 294, etc, or use inst.startClient("hostname") or similar
		//inst.startDSClient();  // recommended if running on DS computer; this gets the robot IP from the DS
		while (true) {
			try {
				Thread.sleep(1000);
			} catch (InterruptedException ex) {
				System.out.println("interrupted");
				return;
			}
			double x = xEntry.getDouble(0.0);
			double y = yEntry.getDouble(0.0);
			System.out.println("X: " + x + " Y: " + y);
		}
	}
}
